
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.Energy
---
components: 
  schemas: 
    GreenEnergyGenerator: 
      $ref: "https://smart-data-models.github.io/dataModel.GreenEnergy/GreenEnergyGenerator/model.yaml#/GreenEnergyGenerator"
info: 
  description: |
    Generic model for Green Energy Generator. A device which can generate energy using Solar or Eolic green energy.
    
  title: GreenEnergyGenerator
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - GreenEnergyGenerator
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.GreenEnergy/GreenEnergyGenerator/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.GreenEnergy/GreenEnergyGenerator/examples/example-normalized.json"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
